export const calculatorActions = Object.freeze({
  ADD_HOLIDAY: 'ADD_HOLIDAY',
  REMOVE_HOLIDAY: 'REMOVE_HOLIDAY',
  ADD_PARTICIPANT: 'ADD_PARTICIPANT',
  REMOVE_PARTICIPANT: 'REMOVE_PARTICIPANT',
  SET_ABSENT: 'SET_ABSENT',
  UNSET_ABSENT: 'UNSET_ABSENT',
  CHANGE_PERCENTAGE: 'CHANGE_PERCENTAGE',
  CHANGE_START_DAY: 'CHANGE_START_DAY'
});